sudo: required

language: c

services:
  - docker

before_install:
  - docker info
  - docker build -t phenompeople/centos-python:3.5.2 3.5.2/

script:
  - docker run -it --rm phenompeople/centos-python:3.5.2 python3 --version